/*leftNav_id不可重复、以下属性名不可更改，否则页面要进行相应调整*/
/*维修yw*/
var leftNav1 = [{
	"text": "维修救援",
	"leftNav_id": "1",
	"name": "维修接车",
	"href": "html/yw/所有维修接车.html"
}, {
	"text": "维修救援",
	"leftNav_id": "2",
	"name": "竣工检验",
	"href": "html/yw/竣工检验.html"
}, {
	"text": "维修救援",
	"leftNav_id": "13",
	"name": "出场放行",
	"href": "html/yw/roles.html"
}, {
	"text": "维修救援",
	"leftNav_id": "24",
	"name": "施工登记",
	"href": "html/yw/kecheng/index.html"
}, {
	"text": "三包索赔",
	"leftNav_id": "26",
	"name": "索赔登记",
	"href": "html/yw/messageList.html"
}, {
	"text": "三包索赔",
	"leftNav_id": "3",
	"name": "索赔申报",
	"href": "html/yw/activity.html"
}, {
	"text": "三包索赔",
	"leftNav_id": "4",
	"name": "三包品返厂",
	"href": "html/yw/ItemsSys/index.html"
}, {
	"text": "三包索赔",
	"leftNav_id": "5",
	"name": "未回三包品",
	"href": "html/yw/ItemsSys/projectteam.html"
}, {
	"text": "三包索赔",
	"leftNav_id": "23",
	"name": "确认索赔",
	"href": "html/yw/ItemsSys/projectcheck.html"
}, {
	"text": "三包索赔",
	"leftNav_id": "6",
	"name": "索赔统计",
	"href": "html/yw/jobSys/jianchazuoye.html"
}, {
	"text": "业务分析",
	"leftNav_id": "7",
	"name": "维修监管",
	"href": "html/yw/jobSys/fabuzuoye.html"
}, {
	"text": "业务分析",
	"leftNav_id": "10",
	"name": "误工率统计",
	"href": "html/yw/classSys/ClassViewAll.html"
}, {
	"text": "业务分析",
	"leftNav_id": "12",
	"name": "返工率统计",
	"href": "html/yw/classSys/Auditing.html"
}];
/*前台*/
var leftNav2 = [{
	"text": "前台结算",
	"leftNav_id": "1",
	"name": "结算中心",
	"href": "html/yw/结算中心.html"
}, {
	"text": "前台结算",
	"leftNav_id": "2",
	"name": "快修通道",
	"href": "html/yw/students.html"
}, {
	"text": "前台结算",
	"leftNav_id": "13",
	"name": "维修退货",
	"href": "html/yw/roles.html"
}, {
	"text": "前台结算",
	"leftNav_id": "24",
	"name": "其他收入",
	"href": "html/yw/kecheng/index.html"
}, {
	"text": "前台结算",
	"leftNav_id": "26",
	"name": "预收定金",
	"href": "html/yw/messageList.html"
}, {
	"text": "收益统计",
	"leftNav_id": "3",
	"name": "结算资金统计",
	"href": "html/yw/activity.html"
}, {
	"text": "收益统计",
	"leftNav_id": "4",
	"name": "销售收入统计",
	"href": "html/yw/ItemsSys/index.html"
}, {
	"text": "收益统计",
	"leftNav_id": "5",
	"name": "结算分类统计",
	"href": "html/yw/ItemsSys/projectteam.html"
}, {
	"text": "收益统计",
	"leftNav_id": "23",
	"name": "附加项目统计",
	"href": "html/yw/ItemsSys/projectcheck.html"
}, {
	"text": "收益统计",
	"leftNav_id": "6",
	"name": "其他收入统计",
	"href": "html/yw/jobSys/jianchazuoye.html"
}, {
	"text": "业绩考核",
	"leftNav_id": "7",
	"name": "服务业绩统计",
	"href": "html/yw/jobSys/fabuzuoye.html"
}, {
	"text": "业绩考核",
	"leftNav_id": "10",
	"name": "维修班组业绩",
	"href": "html/yw/classSys/ClassViewAll.html"
}, {
	"text": "业绩考核",
	"leftNav_id": "12",
	"name": "维修技工业绩",
	"href": "html/yw/classSys/Auditing.html"
}, {
	"text": "卡管理",
	"leftNav_id": "14",
	"name": "储值卡余额表",
	"href": "html/yw/classSys/Auditing.html"
}, {
	"text": "卡管理",
	"leftNav_id": "15",
	"name": "卡销售统计表",
	"href": "html/yw/classSys/Auditing.html"
}, {
	"text": "其他统计",
	"leftNav_id": "16",
	"name": "面单查询",
	"href": "html/yw/classSys/Auditing.html"
}, {
	"text": "其他统计",
	"leftNav_id": "17",
	"name": "优惠查询",
	"href": "html/yw/classSys/Auditing.html"
}, {
	"text": "其他统计",
	"leftNav_id": "18",
	"name": "附单查询",
	"href": "html/yw/classSys/Auditing.html"
}];
/*客户*/
var leftNav3 = [{
	"text": "客户档案",
	"leftNav_id": "1",
	"name": "客户资料",
	"href": "html/oyxy/employees.html"
}, {
	"text": "客户档案",
	"leftNav_id": "2",
	"name": "车辆资料",
	"href": "html/oyxy/students.html"
}, {
	"text": "会员管理",
	"leftNav_id": "13",
	"name": "积分规则",
	"href": "html/oyxy/roles.html"
}, {
	"text": "会员管理",
	"leftNav_id": "24",
	"name": "会员变迁",
	"href": "html/oyxy/index.html"
},{
	"text": "会员管理",
	"leftNav_id": "333",
	"name": "会员查询",
	"href": "html/yw/会员查询.html"
}, {
	"text": "会员管理",
	"leftNav_id": "26",
	"name": "积分赠送",
	"href": "html/oyxy/messageList.html"
}, {
	"text": "客户回访",
	"leftNav_id": "3",
	"name": "维修单据回访",
	"href": "html/oyxy/activity.html"
}, {
	"text": "客户回访",
	"leftNav_id": "4",
	"name": "客户会员回访",
	"href": "html/oyxy/ItemsSys/index.html"
}, {
	"text": "客户回访",
	"leftNav_id": "5",
	"name": "随机回访等级",
	"href": "html/oyxy/ItemsSys/projectteam.html"
}, {
	"text": "客户回访",
	"leftNav_id": "23",
	"name": "回访单据查询",
	"href": "html/oyxy/ItemsSys/projectcheck.html"
}, {
	"text": "客户回访",
	"leftNav_id": "6",
	"name": "回访结果分析",
	"href": "html/oyxy/jobSys/jianchazuoye.html"
}, {
	"text": "客户回访",
	"leftNav_id": "7",
	"name": "抱怨跟踪处理",
	"href": "html/oyxy/jobSys/fabuzuoye.html"
}, {
	"text": "客户回访",
	"leftNav_id": "10",
	"name": "抱怨分项统计",
	"href": "html/oyxy/classSys/ClassViewAll.html"
}, {
	"text": "客户回访",
	"leftNav_id": "12",
	"name": "业务员满意度",
	"href": "html/oyxy/classSys/Auditing.html"
}, {
	"text": "客户回访",
	"leftNav_id": "14",
	"name": "满意度明细",
	"href": "html/oyxy/classSys/ClassViewAll.html"
}, {
	"text": "客户回访",
	"leftNav_id": "15",
	"name": "调查项目",
	"href": "html/oyxy/classSys/Auditing.html"
}, {
	"text": "客户回访",
	"leftNav_id": "16",
	"name": "评定等级",
	"href": "html/oyxy/classSys/ClassViewAll.html"
}, {
	"text": "客户回访",
	"leftNav_id": "17",
	"name": "抱怨项目",
	"href": "html/oyxy/classSys/Auditing.html"
}, {
	"text": "微信营销",
	"leftNav_id": "7",
	"name": "微信预约客户",
	"href": "html/oyxy/jobSys/fabuzuoye.html"
}, {
	"text": "微信营销",
	"leftNav_id": "10",
	"name": "微信救援客户",
	"href": "html/oyxy/classSys/ClassViewAll.html"
}, {
	"text": "微信营销",
	"leftNav_id": "12",
	"name": "微信订单查询",
	"href": "html/oyxy/classSys/Auditing.html"
}, {
	"text": "微信营销",
	"leftNav_id": "14",
	"name": "代金券查询",
	"href": "html/oyxy/classSys/ClassViewAll.html"
}, {
	"text": "微信营销",
	"leftNav_id": "15",
	"name": "服务评价查询",
	"href": "html/oyxy/classSys/Auditing.html"
}, {
	"text": "微信营销",
	"leftNav_id": "16",
	"name": "评价分项统计",
	"href": "html/oyxy/classSys/ClassViewAll.html"
}, {
	"text": "微信营销",
	"leftNav_id": "17",
	"name": "不满意跟踪",
	"href": "html/oyxy/classSys/Auditing.html"
}];
/*数据*/
var leftNav4 = [{
	"text": "主数据",
	"leftNav_id": "1",
	"name": "发动机品牌",
	"href": "html/mj/发动机品牌.html"
}, {
	"text": "主数据",
	"leftNav_id": "2",
	"name": "车型档案",
	"href": "html/mj/品牌车型.html"
}, {
	"text": "主数据",
	"leftNav_id": "13",
	"name": "维修项目",
	"href": "html/mj/维修项目.html"
}, {
	"text": "主数据",
	"leftNav_id": "24",
	"name": "商品资料",
	"href": "html/mj/ComInformation.html"
}, {
	"text": "主数据",
	"leftNav_id": "26",
	"name": "供货单位",
	"href": "html/mj/Supplier.html"
}, {
	"text": "卡定义",
	"leftNav_id": "3",
	"name": "储值卡种类",
	"href": "html/mj/activity.html"
}, {
	"text": "代办数据",
	"leftNav_id": "4",
	"name": "险种定义",
	"href": "html/mj/ItemsSys/index.html"
}, {
	"text": "代办数据",
	"leftNav_id": "5",
	"name": "保险公司",
	"href": "html/mj/ItemsSys/projectteam.html"
}, {
	"text": "其他数据",
	"leftNav_id": "23",
	"name": "可选择项",
	"href": "html/mj/ItemsSys/projectcheck.html"
}];
/*人事*/
var leftNav5 = [{
	"text": "员工资料",
	"leftNav_id": "1",
	"name": "组织机构",
	"href": "html/qyw/员工机构.html"
}, {
	"text": "员工资料",
	"leftNav_id": "2",
	"name": "岗位定义",
	"href": "html/qyw/gangweidingyi.html"
}, {
	"text": "员工资料",
	"leftNav_id": "13",
	"name": "离职登记",
	"href": "html/qyw/lizhidengji.html"
}, {
	"text": "员工资料",
	"leftNav_id": "24",
	"name": "通讯名录",
	"href": "html/qyw/tongxunminglu.html"
}, {
	"text": "技工管理",
	"leftNav_id": "26",
	"name": "技工星级",
	"href": "html/oyxy/技工星级主页面.html"
}, {
	"text": "技工管理",
	"leftNav_id": "3",
	"name": "班组技工",
	"href": "html/oyxy/班组技工.html"
}, {
	"text": "技工管理",
	"leftNav_id": "4",
	"name": "外勤车辆",
	"href": "html/oyxy/外勤车辆.html"
}, {
	"text": "维修工具",
	"leftNav_id": "5",
	"name": "维修工具入库",
	"href": "html/oyxy/ItemsSys/projectteam.html"
}, {
	"text": "维修工具",
	"leftNav_id": "23",
	"name": "维修工具领用",
	"href": "html/oyxy/ItemsSys/projectcheck.html"
}, {
	"text": "维修工具",
	"leftNav_id": "6",
	"name": "工具入库统计",
	"href": "html/oyxy/jobSys/jianchazuoye.html"
}, {
	"text": "维修工具",
	"leftNav_id": "7",
	"name": "工具领用统计",
	"href": "html/oyxy/jobSys/fabuzuoye.html"
}, {
	"text": "维修工具",
	"leftNav_id": "10",
	"name": "工具库存统计",
	"href": "html/oyxy/classSys/ClassViewAll.html"
}, {
	"text": "维修工具",
	"leftNav_id": "12",
	"name": "工具用品定义",
	"href": "html/oyxy/classSys/Auditing.html"
}, {
	"text": "办公用品",
	"leftNav_id": "24",
	"name": "办公用品入库",
	"href": "html/oyxy/ItemsSys/projectcheck.html"
}, {
	"text": "办公用品",
	"leftNav_id": "26",
	"name": "办公用品统计",
	"href": "html/oyxy/jobSys/jianchazuoye.html"
}, {
	"text": "办公用品",
	"leftNav_id": "27",
	"name": "用品入库统计",
	"href": "html/oyxy/jobSys/fabuzuoye.html"
}, {
	"text": "办公用品",
	"leftNav_id": "20",
	"name": "用品领用统计",
	"href": "html/oyxy/classSys/ClassViewAll.html"
}, {
	"text": "办公用品",
	"leftNav_id": "22",
	"name": "用品库存统计",
	"href": "html/oyxy/classSys/Auditing.html"
}];